# Generated by Django 5.1.7 on 2025-05-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
