# Generated by Django 5.2 on 2025-04-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='formations_participees', to='management.employe'),
        ),
    ]
