# Generated by Django 5.2 on 2025-04-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_formation_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='evenements',
            field=models.ManyToManyField(blank=True, related_name='employes', to='management.evenement'),
        ),
        migrations.AddField(
            model_name='employe',
            name='formations',
            field=models.ManyToManyField(blank=True, related_name='employes', to='management.formation'),
        ),
    ]
