# Generated by Django 5.1.7 on 2025-05-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_formulaire_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='categorie',
            field=models.CharField(default='Technique', max_length=100),
        ),
    ]
