# Generated by Django 5.1.7 on 2025-05-24 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_competence_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_participation', models.CharField(choices=[('formation', 'Formation'), ('evenement', 'Événement')], max_length=10)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(default='Affecté', max_length=50)),
                ('source', models.CharField(default='Affectation Admin', max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='management.employe')),
            ],
        ),
    ]
