# Generated by Django 5.2 on 2025-04-07 19:36

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_employe_evenements_employe_formations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=management.models.CustomUser.user_profile_picture_path),
        ),
    ]
