# Generated by Django 5.2 on 2025-04-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='date_join',
            field=models.DateField(blank=True, null=True),
        ),
    ]
